### ISSUE TITLE
Bug on YouTube video page

### ISSUE THREAD

**Issue by davidhedlund** [turnoffthelights/Turn-Off-the-Lights-Firefox-extension#1]
@turnoffthelights The layout breaks in https://www.youtube.com/watch?v=esuTD79Nb8U but only with Turn Off the Lights enabled.

**Comment by turnoffthelights** [comment]
Do you use Turn Off the Lights v3.1.0.27 that is the latest version. https://addons.mozilla.org/en-US/firefox/addon/turn-off-the-lights/versions/
